name: Fully Automated DNS Migration

on:
  workflow_dispatch:

jobs:
  migrate-dns:
    runs-on: ubuntu-latest

    env:
      SOURCE_DOMAIN: devopsengg.xyz

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install cli53 binary (v0.8.23)
      run: |
        mkdir -p $HOME/.local/bin
        wget https://github.com/barnybug/cli53/releases/download/0.8.23/cli53-linux-amd64 \
          -O $HOME/.local/bin/cli53
        chmod +x $HOME/.local/bin/cli53
        echo "$HOME/.local/bin" >> $GITHUB_PATH



    - name: Export DNS Records from Route 53
      run: |
        mkdir -p export
        cli53 export --full devopsengg.xyz > export/records.txt
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


    - name: Generate Terraform records.tf from export
      run: |
        python3 scripts/convert.py export/records.txt terraform/records.tf

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: terraform/

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="domain_name=devopsengg.xyz"
      working-directory: terraform/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.TARGET_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TARGET_AWS_SECRET_ACCESS_KEY }}
